-- ============================================
-- Applications table (your schema, with suggestions)
-- ============================================
-- Suggestions:
-- 1. Add email text NOT NULL — you need it to contact applicants.
-- 2. Add resume_path text NULL — storage path after upload (e.g. "resumes/abc123_resume.pdf").
-- 3. grad_year: date is fine if you store a single day (e.g. 2026-06-01 for "Class of 2026").
--    If you prefer "2026" or "graduated" as text, use text instead of date.
-- 4. id: bigint identity is fine; uuid is an option if you want non-sequential IDs.

create table if not exists public.applications (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  first text null,
  last text null,
  email text null unique,             -- required for contacting applicants
  school text null,
  grad_year date null,
  resume_path text null,             -- path in Storage bucket, e.g. "resumes/uuid_filename.pdf"
  constraint applications_pkey primary key (id)
);

-- RLS: no anon insert; Edge Function uses service role to insert
alter table public.applications enable row level security;
-- (No policies = only service role can read/insert.)

-- ============================================
-- Storage bucket for resumes
-- ============================================
-- 1. In Dashboard → Storage: create a bucket named "resumes", Private, optional 5 MB limit, MIME: pdf, doc, docx.
-- 2. Then run the policies below in SQL Editor.

-- Policy: allow anyone (anon) to upload only under prefix "resumes/"
-- So object names must be like "resumes/xyz.pdf". Use a unique path per submission (e.g. "resumes/{uuid}_filename.pdf").
create policy "Allow anon upload under resumes/"
on storage.objects for insert
to anon
with check (
  bucket_id = 'resumes'
  and (storage.foldername(name))[1] = 'resumes'
);

-- Optional: allow authenticated (e.g. you) to read all; anon cannot list or read
create policy "Allow authenticated read resumes"
on storage.objects for select
to authenticated
using (bucket_id = 'resumes');

-- Service role can do anything (by default), so Edge Function can read/insert.

-- ============================================
-- If you already have public.applications without email/resume_path, add columns:
-- ============================================
-- alter table public.applications add column if not exists email text null;
-- alter table public.applications add column if not exists resume_path text null;
